spring.application.name=flightos-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/flightos
spring.datasource.username=postgres
spring.datasource.password=${FLIGHTOS_DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info